resources:
  repositories:
    - repository: infraAzurePipelines
      type: git
      name: P-Data-Hub-Infra-CI-CD
      ref: refs/tags/v10.0.0
trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - cloud-formation/rds/azure-pipelines/cd.yaml
      - cloud-formation/rds/cloud-formation.yaml
extends:
  template: cloud-formation/template/rds/cd/deploy-instances.yaml@infraAzurePipelines
  parameters:
    devInstanceNames: [main]
    intInstanceNames: [main]
    prodInstanceNames: [main]
    stackNamePrefix: pfm-infra-plm
    serviceName: plm
    dataClassificationLabel: red
    teamName: Echo
