parameters:
  - name: name
    type: string
  - name: runArguments
    type: string
steps:
  - task: Docker@2
    displayName: Start ${{ parameters.name }} image
    inputs:
      command: run
      arguments: --detach ${{ parameters.runArguments }}





